const EXTRA_COLORS = [
	{ label: 'Graphite', value: '#393e46' },
	{ label: 'Slate', value: '#64748b' },
	{ label: 'Cloud', value: '#eeeeee' },
	{ label: 'White', value: '#ffffff' },
	{ label: 'Ocean', value: '#00adb5' },
	{ label: 'Sky', value: '#3abef9' },
	{ label: 'Mint', value: '#95e1d3' },
	{ label: 'Leaf', value: '#16a34a' },
	{ label: 'Lime \u00b7 Soft', value: '#a3e635' },
	{ label: 'Sage', value: '#a8df8e' },
	{ label: 'Gold \u00b7 Soft', value: '#f9b572' },
	{ label: 'Coral', value: '#ff6b6b' },
	{ label: 'Rose', value: '#ff4d6d' },
	{ label: 'Pink', value: '#f875aa' },
	{ label: 'Fuchsia', value: '#c23373' },
	{ label: 'Purple \u00b7 Soft', value: '#7c3aed' },
	{ label: 'Lavender', value: '#a78bfa' },
	{ label: 'Peach', value: '#ffd6a5' },
	{ label: 'Cream', value: '#fff3da' },
	{ label: 'Sand', value: '#e9c46a' },
];

export type ColorGroup = { label: string; items: Array<{ label: string; value: string }> };
export const COLOR_GROUPS: ColorGroup[] = [
 { label: 'Standard', items: [
  { label: 'Blue', value: '#0000ff' },
  { label: 'Dark Blue', value: '#00008b' },
  { label: 'Navy', value: '#000080' },
  { label: 'Royal Blue', value: '#4169e1' },
  { label: 'Dodger Blue', value: '#1e90ff' },
  { label: 'Deep Sky Blue', value: '#00bfff' },
  { label: 'Cyan', value: '#00ffff' },
  { label: 'Teal', value: '#008080' },
  { label: 'Green', value: '#008000' },
  { label: 'Lime', value: '#00ff00' },
  { label: 'Dark Green', value: '#006400' },
  { label: 'Olive', value: '#808000' },
  { label: 'Yellow', value: '#ffff00' },
  { label: 'Gold', value: '#ffd700' },
  { label: 'Orange', value: '#ffa500' },
  { label: 'Dark Orange', value: '#ff8c00' },
  { label: 'Red', value: '#ff0000' },
  { label: 'Maroon', value: '#800000' },
  { label: 'Magenta', value: '#ff00ff' },
  { label: 'Purple', value: '#800080' },
  { label: 'Black', value: '#000000' },
  { label: 'Gray', value: '#808080' },
  { label: 'Silver', value: '#c0c0c0' },
  { label: 'Dark Gray', value: '#a9a9a9' },
 ] },
 { label: 'Extra', items: EXTRA_COLORS },
 { label: 'Nature', items: [
  { label: 'Nature 1', value: '#007a4d' },
  { label: 'Nature 2', value: '#00875a' },
  { label: 'Nature 3', value: '#248a45' },
  { label: 'Nature 4', value: '#65b820' },
  { label: 'Nature 5', value: '#95c93d' },
  { label: 'Nature 6', value: '#b7d76a' },
  { label: 'Nature 7', value: '#dce6aa' },
  { label: 'Nature 8', value: '#edf8d1' },
 ] },
 { label: 'Sea & sky', items: [
  { label: 'Sea & sky 1', value: '#27699b' },
  { label: 'Sea & sky 2', value: '#398ba0' },
  { label: 'Sea & sky 3', value: '#5aaed6' },
  { label: 'Sea & sky 4', value: '#87c5c9' },
  { label: 'Sea & sky 5', value: '#b2e3f3' },
  { label: 'Sea & sky 6', value: '#c5e8f2' },
  { label: 'Sea & sky 7', value: '#dff1f5' },
  { label: 'Sea & sky 8', value: '#eef8fa' },
 ] },
 { label: 'Warm', items: [
  { label: 'Warm 1', value: '#ff6908' },
  { label: 'Warm 2', value: '#cf801b' },
  { label: 'Warm 3', value: '#ff4d50' },
  { label: 'Warm 4', value: '#f56fa6' },
  { label: 'Warm 5', value: '#ffce86' },
  { label: 'Warm 6', value: '#ffe76b' },
  { label: 'Warm 7', value: '#ffe5be' },
  { label: 'Warm 8', value: '#fff4d9' },
 ] },
];
export const COLOR_PALETTE = COLOR_GROUPS.flatMap(group => group.items);
